name: CICD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t sarindump/weather-microservice-api .
      - name: Publish image to docker hub
        run: docker push sarindump/weather-microservice-api:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull sarindump/weather-microservice-api:latest
      - name: Delete old container
        run: docker rm -f weather-microservice-api-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name weather-microservice-api-container sarindump/ms-property-listings-api
